spring.application.name=api-test

# Endpoint-specific configuration

rate-limiter.endpoints.login.limit=6
rate-limiter.endpoints.login.time-window-seconds=60

rate-limiter.endpoints.users.limit=1
rate-limiter.endpoints.users.time-window-seconds=60